### PR TITLE
Frontend Changes/Other Organizations

### PR DESCRIPTION
**Pull request by Robert430404**
screen shot 2017-01-16 at 2 10 43 pm

Did a lot of refinements to the CSS/JS and homepage HTML structure. Also formatted a few things in the scripts as I was reading through it. Also sectioned out the views into pages and partials for future refinements.

### CODE REVIEW

**Comment by Robert430404** [comment]
I would have done more, but didn't have any seed data to work with, if I could get some that would be great!

**Comment by chadicus** [comment]
This is amazing.  I've created a gist containing a copy of the libraries collection you can find it [here](https://gist.github.com/chadicus/35d3abfa5e4a06e80874d63f521ad0e4)  I've commented instructions on how to import the file into mongo locally.  Hope this helps

**Comment by chadicus** [comment]
@Robert430404  do you have any libraries you would like me to load into the database? I will gladly add them for your contribution.

**Comment by Robert430404** [comment]
@chadicus the only thing I have thats of any use to someone else is an SDK I wrote for a sprint car API for my company that they let me open source, if you want to add it you can.

https://github.com/Robert430404/mrp-php-sdk

I'll do some more work as time permits, I can really dig in now that I have some data to work with! Thanks for that! Expect to see more pulls as time permits.

**Comment by chadicus** [comment]
Done

http://www.pholiophp.org/robert430404/mrp-php-sdk

Thanks again for the frontend work.

**Pull request merged**
